eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: gateway
server:
  port: 8083
zuul:
  routes:
    consumer: /c/**
    provider: /p/**

