eureka:
  instance:
    hostname: ${HOSTNAME:localhost} 
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
spring:
  application:
    name: gateway
server:
  port: 8083
zuul:
  routes:
    consumer: /c/**
    provider: /p/**

