spring:
  application:
    name: consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/  #注册中心地址
  instance:
    hostname: ${HOSTNAME:localhost} 
    instance-id: http://${spring.application.name}:8082
server:
  port: 8082
