spring:
  application:
    name: consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA:localhost}:${EUREKA_PORT:8761}/eureka/  #注册中心地址
  instance:
    hostname: ${HOSTNAME:localhost} 
    #instance-id: http://${spring.application.name}:8082
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}:@project.version@
server:
  port: 8082
